# Generated by Django 5.2.14 on 2026-05-18 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('niche', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('instagram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='creators/profile-images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['created_at'], name='creators_cr_created_daed44_idx')],
            },
        ),
    ]
