# Generated by Django 5.2.14 on 2026-05-18 10:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='submissions/content/')),
                ('caption', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVISION_REQUESTED', 'Revision requested'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=30)),
                ('brand_feedback', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='campaigns.campaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='creators.creatorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='submissions_status_19bf79_idx'), models.Index(fields=['created_at'], name='submissions_created_fcb5eb_idx')],
            },
        ),
    ]
